import Login from "@/components/Login/Login/Login";
import Head from "next/head";

export default function Index() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="common-layout">
        <Login/>
      </div>
    </>
  );
}
